# Generated by Django 4.2.17 on 2025-12-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_skill_profile_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subjects',
        ),
        migrations.AddField(
            model_name='profile',
            name='subjects',
            field=models.TextField(blank=True),
        ),
    ]
